
;--------------------------------------
; System Equates
;--------------------------------------

ADLI            = $0080
AVB             = $0040
ALMS            = $0040
AJMP            = $0001
AEMPTY3         = $0020
AEMPTY8         = $0070

ATTRACT         = $004D

DMACTL          = $022F
DLISTL          = $0230
PRIOR           = $026F
STICK           = $0278
STRIG           = $0284
COLPM0          = $02C0
COLPM3          = $02C3
COLPF0          = $02C4
COLPF1          = $02C5
COLPF2          = $02C6
COLPF3          = $02C7
COLBK           = $02C8
KEY             = $02FC

HPOSP0          = $D000
HPOSP3          = $D003
P0PF            = $D004
P0PL            = $D00C
GRACTL          = $D01D
HITCLR          = $D01E
CONSOL          = $D01F

AUDF1           = $D200
AUDC1           = $D201
AUDF2           = $D202
AUDC2           = $D203
AUDF3           = $D204
AUDC3           = $D205
AUDF4           = $D206
AUDC4           = $D207
AUDCTL          = $D208
RANDOM          = $D20A

PMBASE          = $D407
NMIEN           = $D40E

SETVBV          = $E45C
XITVBV          = $E45F
